services:
  _defaults: {autowire: true, autoconfigure: true}

  AppBundle\Grid\Car\CarEndpoint: ~
  AppBundle\Grid\Engine\EngineEndpoint: ~
  AppBundle\Grid\Github\GithubEndpoint: ~
  AppBundle\Grid\Color\ColorEndpoint: ~
  AppBundle\Grid\Country\CountryEndpoint: ~

  AppBundle\Bridge\Grid\Filter\Entity\Select2EntityFilter: ~
  AppBundle\Bridge\Grid\Filter\Linq\LinqStringFilter: ~
  AppBundle\Bridge\Grid\Filter\Linq\LinqBooleanFilter: ~
  AppBundle\Bridge\Grid\Field\HtmlImageField: ~

  AppBundle\Controller\MainPageEndpoint: ~